import type { Metadata } from "next";
import { Roboto as Font } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import { SidebarProvider } from "../contexts/SidebarContext";
import "./globals.css";

const font = Font({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ChakraProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}